//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoActivity.Support {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoActivity.Support.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string kBackTextKey {
            get {
                return ResourceManager.GetString("kBackTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string kEditTextKey {
            get {
                return ResourceManager.GetString("kEditTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in GPS =.
        /// </summary>
        internal static string kErrorForGPSFailureKey {
            get {
                return ResourceManager.GetString("kErrorForGPSFailureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Network =.
        /// </summary>
        internal static string kErrorForNetworkFailureKey {
            get {
                return ResourceManager.GetString("kErrorForNetworkFailureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS will not be available for Application due denial of GPS permission!.
        /// </summary>
        internal static string kGPSPermissionMessageKey {
            get {
                return ResourceManager.GetString("kGPSPermissionMessageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get location:.
        /// </summary>
        internal static string kLocationFetchFailedMessageKey {
            get {
                return ResourceManager.GetString("kLocationFetchFailedMessageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location access is required to read current location..
        /// </summary>
        internal static string kLocationPermissionMessageKey {
            get {
                return ResourceManager.GetString("kLocationPermissionMessageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string kMessageTextKey {
            get {
                return ResourceManager.GetString("kMessageTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string kNewTextKey {
            get {
                return ResourceManager.GetString("kNewTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string kOkTextKey {
            get {
                return ResourceManager.GetString("kOkTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string kSaveTextKey {
            get {
                return ResourceManager.GetString("kSaveTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select future time!.
        /// </summary>
        internal static string kSelectTimeAlertKey {
            get {
                return ResourceManager.GetString("kSelectTimeAlertKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string kTitleTextKey {
            get {
                return ResourceManager.GetString("kTitleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string kViewTextKey {
            get {
                return ResourceManager.GetString("kViewTextKey", resourceCulture);
            }
        }
    }
}
